# Generated by Django 5.1.3 on 2024-11-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authenticator',
            table='db_authenticator',
        ),
        migrations.AlterModelTable(
            name='user',
            table='db_user',
        ),
    ]
